### ISSUE TITLE
Jest Error: SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by lk-jeffpeck** [olup/react-hook-mousetrap#5]
I am running into the following issue with jest and I am wondering if anyone has seen this before with react-hook-mousetrap?
```
src/components/MyComponent/MyComponent.spec.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /path/to/node_modules/react-hook-mousetrap/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import mousetrap from "mousetrap";
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      4 | import range from 'lodash/range';
      5 | import { Button, Icon, Input } from '../../../Styled';
    > 6 | import useMousetrap from 'react-hook-mousetrap';
        | ^
      7 | 
      8 | import { RangeSlider } from '../RangeSlider';
      9 | 

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1270:14)
      at Object.<anonymous> (src/path/to/MyComponent.jsx:6:1)
```

**Comment by lk-jeffpeck** [comment]
This fixed it, inside jest.config.js:
```
  transformIgnorePatterns: [
    'node_modules/(?!react-hook-mousetrap/.*)',
  ],
```
